server:
  port: 12000

spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Evil-LGX/tensquare-config.git
  rabbitmq:
    host: localhost

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh