server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: localhost
  cloud:
    refresh:
      refreshable: none

aliyun:
  sms:
    accessKeyId: 
    accessKeySecret: 
    template_code: 
    sign_name: 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true